import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

function replaceAll(content, replacements) {
  let next = content;
  for (const [from, to] of replacements) {
    next = next.split(from).join(to);
  }
  return next;
}

function updateFile(relativePath, replacements) {
  const filePath = resolve(process.cwd(), relativePath);
  const original = readFileSync(filePath, "utf8");
  const next = replaceAll(original, replacements);
  if (next !== original) {
    writeFileSync(filePath, next, "utf8");
  }
}

updateFile("FE/src/components/AdminWorkspace.tsx", [
  ["Sửa", "編集"],
  ["Xóa", "削除"],
  ["Mật khẩu", "パスワード"],
  ["Nguồn: IQAir", "出典: IQAir"],
  ["Đang hoạt động", "稼働中"],
  ["đang hoạt động", "稼働中"],
  ["Mở cửa", "営業中"],
  ["Hà Nội - chọn vị trí trên bản đồ", "ハノイ - 地図上で位置を選択"],
  ["スポットを追加 mới", "新しいスポットを追加"],
  ["すべて bình luận", "すべてのコメント"],
  ["Đã xác nhận", "確認済み"],
  ["Trạm nước", "給水所"],
  ["Bóng râm", "日陰"],
  ["Nhà vệ sinh", "トイレ"],
  ["Ghế ngồi", "ベンチ"],
  ["Tốt", "良好"],
  ["Trung bình", "普通"],
  ["Kém", "悪い"],
  ["Xấu", "非常に悪い"],
  ["Ẩn danh", "匿名"],
  ["Trình duyệt không hỗ trợ định vị GPS.", "ブラウザは GPS 位置情報をサポートしていません。"],
  ["Trình duyệt đã chặn vị trí GPS. Mở cài đặt trình duyệt để cho phép.", "ブラウザが GPS 位置情報をブロックしています。ブラウザ設定で許可してください。"],
  ["Không thể tải AQI hệ thống từ IQAir.", "IQAir からシステム AQI を取得できませんでした。"],
  ["Không thể tải danh sách địa điểm.", "スポット一覧を読み込めませんでした。"],
  ["Cơ sở chưa đặt tên", "未設定の施設"],
  ["Tất cả", "すべて"],
  ["Vui lòng nhập tên địa điểm.", "スポット名を入力してください。"],
  ["Vui lòng nhập tọa độ hợp lệ.", "有効な座標を入力してください。"],
  ["Đã cập nhật địa điểm.", "スポットを更新しました。"],
  ["Đã tạo địa điểm mới.", "新しいスポットを作成しました。"],
  ["Không thể lưu địa điểm.", "スポットを保存できませんでした。"],
  ["Xóa địa điểm này?", "このスポットを削除しますか？"],
  ["Đã xóa địa điểm.", "スポットを削除しました。"],
  ["Không thể xóa địa điểm.", "スポットを削除できませんでした。"],
  ["Không thể cập nhật bình luận.", "コメントを更新できませんでした。"],
  ["Chào mừng trở lại, quản trị viên", "おかえりなさい、管理者"],
  ["Tổng quan hệ thống", "システム概要"],
  ["AQI hệ thống", "システム AQI"],
  ["Nguồn: hệ thống / IQAir", "出典: システム / IQAir"],
  ["Hà Nội", "ハノイ"],
  ["Hoạt động hệ thống", "システムアクティビティ"],
  ["Người dùng hoạt động 7 ngày gần đây", "過去7日間のアクティブユーザー"],
  ["Có nội dung vi phạm cần xử lý", "処理が必要な違反コンテンツがあります"],
  ["Kiểm duyệt nội dung vi phạm", "違反コンテンツを審査"],
  ["Quản lý địa điểm tập thể dục", "運動スポット管理"],
  ["Thêm địa điểm", "スポットを追加"],
  ["Quản lý địa điểm", "スポット管理"],
  ["Đang hoạt động: ", "稼働中: "],
  ["Đang tải địa điểm...", "スポットを読み込み中..."],
  ["Chưa có địa chỉ", "住所未設定"],
  ["Cập nhật: vài phút trước", "更新: 数分前"],
  ["Bật/Tắt hỗ trợ tiếng Nhật", "日本語対応の切り替え"],
  ["Chưa có địa điểm nào trong DB.", "DB にスポットがありません。"],
  ["Thêm địa điểm mới", "新しいスポットを追加"],
  ["Điền thông tin cơ sở, chọn vị trí trên bản đồ và lưu lại để tạo địa điểm mới.", "施設情報を入力し、地図上で位置を選んで保存すると新しいスポットを作成できます。"],
  ["Back về quản lý cơ sở", "施設管理に戻る"],
  ["Hà Nội - chọn vị trí trên bản đồ", "ハノイ - 地図上で位置を選択"],
  ["Vị trí đã chọn", "選択済みの位置"],
  ["Chỉnh sửa địa điểm", "スポットを編集"],
  ["Tạo địa điểm mới", "新しいスポットを作成"],
  ["Thông tin cơ sở", "施設情報"],
  ["Tên địa điểm", "スポット名"],
  ["Địa chỉ", "住所"],
  ["Hỗ trợ tiếng Nhật", "日本語対応"],
  ["Hiển thị như địa điểm gợi ý cho người dùng Nhật", "日本人ユーザー向けのおすすめスポットとして表示"],
  ["Tiện ích chính", "主要設備"],
  ["+ Thêm", "+ 追加"],
  ["Mô tả", "説明"],
  ["Nhập đặc điểm địa điểm hoặc thời gian sử dụng được khuyến nghị...", "スポットの特徴や推奨利用時間を入力してください..."],
  ["Loại địa điểm", "スポット種類"],
  ["Thành phố", "都市"],
  ["Khu / quận", "地区 / 区"],
  ["Đang lưu...", "保存中..."],
  ["Cập nhật", "更新"],
  ["Lưu", "保存"],
  ["Hủy", "キャンセル"],
  ["Quản lý bình luận không phù hợp", "不適切コメント管理"],
  ["Kiểm tra các bình luận vi phạm", "違反コメントを確認します"],
  ["Bộ lọc theo cơ sở", "施設別フィルター"],
  ["Chọn cơ sở có bình luận bị blocklist để lọc nhanh.", "ブロックリスト入りのコメントがある施設を選ぶと素早く絞り込めます。"],
  ["Cơ sở", "施設"],
  ["Tất cả bình luận", "すべてのコメント"],
  ["Chưa xử lý", "未処理"],
  ["Đã xóa", "削除済み"],
  ["Tiếng Việt", "ベトナム語"],
  ["Tiếng Nhật", "日本語"],
  ["Vi phạm ", "違反 "],
  [" lần", " 回"],
  ["Không có bình luận nào khớp bộ lọc.", "フィルターに一致するコメントはありません。"],
  ["Hồ sơ quản trị viên", "管理者プロフィール"],
  ["Đổi avatar", "アバターを変更"],
  ["Quản trị viên hệ thống", "システム管理者"],
  ["Tài khoản đăng nhập: ", "ログインアカウント: "],
  ["Mật khẩu: ", "パスワード: "],
  ["Thông tin cá nhân", "個人情報"],
  ["Họ và tên", "氏名"],
  ["Quản trị viên đã được xác minh", "管理者は認証済みです"],
  ["Danh tính của bạn đã được xác minh hoàn toàn, cho phép truy cập tất cả công cụ quản trị.", "あなたの身元は完全に確認されており、すべての管理ツールにアクセスできます。"],
  ["Chọn avatar", "アバターを選択"],
  ["Close avatar picker", "アバター選択を閉じる"],
  ["Khung", "フレーム"],
  ["Avatar", "アバター"],
  ["Lưu avatar", "アバターを保存"],
  ["Đăng xuất", "ログアウト"],
  ["Phiên bản 2.4.0 - SAFEMOVE HANOI 2024", "バージョン 2.4.0 - SAFEMOVE HANOI 2024"],
  ["Lưu ", "保存 "],
  ["Sửa ", "編集 "],
  ["Không thể tải AQI hệ thống từ IQAir.", "IQAir からシステム AQI を取得できませんでした。"],
]);

updateFile("FE/src/components/WorkspaceScreens.tsx", [
  ["Nguyễn Linh", "リン"],
  ["2 giờ trước", "2時間前"],
  ["1 ngày trước", "1日前"],
  ["3 ngày trước", "3日前"],
  ["Không khí dễ chịu, đường đi thông thoáng và có nhiều cây xanh.", "空気が心地よく、道も開けていて、緑が多いです。"],
  ["Bãi tập rộng, AQI ổn định. Giá như có thêm nhiều ghế nghỉ hơn.", "広い運動エリアで AQI も安定しています。休憩用のベンチがもう少しあると良いです。"],
  ["Giao diện rõ ràng, dễ hiểu, phù hợp để chọn điểm luyện tập ngoài trời.", "画面が見やすく、屋外の運動スポットを選ぶのに適しています。"],
  ["Chỉ số đã vượt ngưỡng cá nhân. 良好 nhất hãy chuyển sang không gian kín hoặc hoãn vận động ngoài trời.", "指標が個人しきい値を超えています。屋内へ移るか、屋外運動を延期してください。"],
  ["すべて thời điểm", "すべての期間"],
  ["Khu trung tâm", "中心地区"],
  ["Lộ trình xanh cần đăng nhập.", "グリーンルートの利用にはログインが必要です。"],
  ["すべて bình luận", "すべてのコメント"],
  ["ログインが必要です để gửi bình luận.", "コメントを送信するにはログインが必要です。"],
  ["通知 đẩy", "プッシュ通知"],
  ["Hoàn Kiếm Gym", "ホアンキエム・ジム"],
  ["Hoàn Kiếm, Hà Nội", "ホアンキエム、ハノイ"],
  ["Hoàn Kiếm, ハノイ", "ホアンキエム、ハノイ"],
  ["絞り込み theo địa điểm", "スポットで絞り込み"],
  ["Lê Minh Anh", "ミン・アン"],
  ["Trạng thái xác thực: <strong>Đã xác nhận</strong>", "認証状態: <strong>確認済み</strong>"],
  ["Chưa xác định vị trí", "位置未確定"],
  ["Đang hoạt động: ", "稼働中: "],
  ["Cập nhật: vài phút trước", "更新: 数分前"],
  ["Xóa", "削除"],
  ["Khôi phục", "復元"],
  ["Tải lại AQI", "AQI を再取得"],
  ["Nhiệt độ", "気温"],
  ["Độ ẩm", "湿度"],
  ["Gió", "風"],
  ["Lời khuyên sức khỏe", "健康アドバイス"],
  ["Thông báo gần đây", "最近の通知"],
  ["Cập nhật mới", "新しい更新"],
  ["Tìm địa điểm", "スポットを探す"],
  ["Từ khóa", "キーワード"],
  ["Bộ lọc", "フィルター"],
  ["Ẩn", "非表示"],
  ["Lọc", "絞り込み"],
  ["Gần đây", "最近"],
  ["Tất cả thời điểm", "すべての期間"],
  ["Đang lọc gần đây", "最近の条件で絞り込み中"],
  ["Hiện tất cả", "すべて表示"],
  ["Địa điểm phù hợp", "該当スポット"],
  ["Nên ưu tiên công viên nhiều cây xanh hoặc phòng tập kín nếu bạn muốn vận động lâu.", "長く運動したい場合は、木の多い公園か屋内ジムを優先してください。"],
  ["Màn hình chi tiết địa điểm và đánh giá", "スポット詳細とレビュー画面"],
  ["Địa điểm được mô tả theo đúng layout tài liệu: hiển thị điểm an toàn, PM2.5, giới thiệu, và nút xem tất cả bình luận.", "ドキュメントのレイアウトどおりに、セーフティスコア、PM2.5、概要、全コメント表示ボタンを表示します。"],
  ["Xem tất cả bình luận", "すべてのコメントを表示"],
  ["Hãy đăng nhập để đăng bài đánh giá", "レビューを投稿するにはログインしてください"],
  ["Hãy nhập đánh giá của bạn", "レビューを入力してください"],
  ["Cần đăng nhập để gửi bình luận.", "コメントを送信するにはログインが必要です。"],
  ["Gửi bình luận", "コメントを送信"],
  ["Bản đồ và tìm đường dành cho người dùng đăng nhập", "ログインユーザー向けの地図とルート検索"],
  ["Địa điểm tập luyện", "運動スポット"],
  ["Mở cửa", "営業中"],
  ["Cảnh báo sức khỏe hiện tại dựa trên chỉ số AQI và điều kiện thời tiết.", "現在の健康警告は AQI と天候条件に基づいています。"],
  ["Phản hồi chuyên gia", "専門家の見解"],
  ["Hạn chế vận động cường độ cao", "高強度運動は控えてください"],
  ["Ưu tiên tuyến đường xanh và cân nhắc không gian trong nhà nếu cảm thấy khó chịu.", "グリーンルートを優先し、違和感がある場合は屋内も検討してください。"],
  ["Hồ sơ và cài đặt", "プロフィールと設定"],
  ["Thành viên SafeMove", "SafeMove メンバー"],
  ["Tình trạng sức khỏe", "健康状態"],
  ["Chưa có dữ liệu tình trạng sức khỏe.", "健康データはまだありません。"],
  ["Thông tin cá nhân", "個人情報"],
  ["Ngưỡng AQI", "AQI しきい値"],
  ["Khi AQI vượt ngưỡng này, ứng dụng sẽ ưu tiên cảnh báo sớm và gợi ý tuyến ít phơi nhiễm hơn.", "このしきい値を超えると、アプリは早めの警告と曝露の少ないルートを優先します。"],
  ["Thông báo", "通知"],
  ["Thông báo đẩy", "プッシュ通知"],
  ["Cập nhật qua email", "メール更新"],
  ["Lưu cài đặt", "設定を保存"],
  ["Đăng xuất", "ログアウト"],
  ["Bảng điều khiển quản trị hệ thống", "システム管理ダッシュボード"],
  ["Quản lý cơ sở", "施設管理"],
  ["Quản lý vi phạm", "違反管理"],
  ["AQI trung bình", "平均 AQI"],
  ["Người dùng hoạt động", "アクティブユーザー"],
  ["Đang chờ xử lý", "処理待ち"],
  ["Cơ sở", "施設"],
  ["Khẩn cấp", "緊急"],
  ["Vi phạm ", "違反 "],
  ["Thống kê nhanh", "クイック統計"],
  ["Avg AQI", "平均 AQI"],
  ["Reports", "レポート"],
  ["Facilities", "施設"],
  ["Trung bình thành phố", "市内平均"],
  ["Cần kiểm duyệt", "審査が必要"],
  ["Đã đăng ký", "登録済み"],
  ["Màn hình quản lý thông tin cơ sở", "施設情報管理画面"],
  ["Thêm cơ sở mới", "新しい施設を追加"],
  ["Màn hình thêm cơ sở mới", "新しい施設追加画面"],
  ["Tên cơ sở", "施設名"],
  ["Không gian xanh, có HEPA", "緑のある空間、HEPA あり"],
  ["Màn hình quản lý bình luận vi phạm", "違反コメント管理画面"],
  ["Lọc theo địa điểm", "スポットで絞り込む"],
  ["Màn hình hồ sơ quản trị viên", "管理者プロフィール画面"],
  ["Xác thực", "認証"],
  ["Quản trị viên hệ thống", "システム管理者"],
  ["Đã xác nhận", "確認済み"],
  ["Họ tên", "氏名"],
  ["Số điện thoại", "電話番号"],
  ["Quyền truy cập", "アクセス権限"],
  ["Bình luận vi phạm số 3", "違反コメント 3"],
  ["Nội dung báo cáo đang chờ xử lý để bảo vệ cộng đồng.", "コミュニティを守るため、報告内容を処理待ちにしています。"],
  ["Bách Thảo Park", "バッハ・トア公園"],
  ["Đánh giá tiêu cực lặp lại", "繰り返しの低評価"],
  ["Nội dung có dấu hiệu spam và cần kiểm duyệt lại.", "スパムの兆候があり、再審査が必要です。"],
  ["Công viên Thống Nhất", "トンニャット公園"],
  ["Tốt", "良好"],
  ["Trung bình", "普通"],
  ["Xấu", "悪い"],
  ["AQI tốt nhưng đã chạm ngưỡng cá nhân", "AQI は良好ですが個人しきい値に達しました"],
  ["Không khí đang tốt", "空気は良好です"],
  ["Chỉ số chung vẫn ổn, nhưng ngưỡng cá nhân của bạn đang khá thấp. Nên giữ cường độ nhẹ.", "全体の指標はまだ安定していますが、あなたの個人しきい値は低めです。軽い強度に保ちましょう。"],
  ["Có thể ra ngoài vận động, ưu tiên các tuyến xanh và theo dõi thay đổi thời tiết.", "外で運動できます。グリーンルートを優先し、天候の変化を確認してください。"],
  ["Cần giảm cường độ vận động", "運動強度を下げる必要があります"],
  ["Không khí ở mức chấp nhận được", "空気は許容範囲です"],
  ["Bạn đã tới vùng AQI cần thận trọng hơn. Hạn chế bài tập dài và ưu tiên khu vực nhiều cây xanh.", "より注意が必要な AQI 域に入っています。長時間の運動は避け、緑の多いエリアを優先してください。"],
  ["Có thể tập nhẹ ngoài trời, nhưng nên rút ngắn thời lượng và theo dõi triệu chứng.", "屋外で軽く運動できますが、時間を短くし、症状を確認してください。"],
  ["Nên chuyển sang hoạt động trong nhà", "屋内活動へ切り替えるべきです"],
  ["AQI đang xấu", "AQI が悪化しています"],
  ["Chỉ số đã vượt ngưỡng cá nhân. Tốt nhất hãy chuyển sang không gian kín hoặc hoãn vận động ngoài trời.", "指標が個人しきい値を超えています。屋内へ移るか、屋外運動を延期してください。"],
  ["Hạn chế ra ngoài lâu. Nếu cần di chuyển, hãy chọn lộ trình ngắn và ít tiếp xúc không khí hơn.", "長時間の外出は控えてください。移動が必要なら、短くて曝露の少ないルートを選びましょう。"],
  ["Bạn cần đăng nhập để tiếp tục.", "続行するにはログインが必要です。"],
  ["Tất cả", "すべて"],
  ["Công viên", "公園"],
  ["Yêu thích", "お気に入り"],
  ["Cần đăng nhập", "ログインが必要です"],
  ["Đăng nhập", "ログイン"],
  ["Hủy", "キャンセル"],
  ["Trang chủ", "ホーム"],
  ["Quản trị", "管理者"],
  ["Khách", "ゲスト"],
  ["Người dùng", "ユーザー"],
  ["Chưa xác định vị trí", "位置未確定"],
  ["Tải lại AQI", "AQI を再取得"],
  ["Nhiệt độ", "気温"],
  ["Độ ẩm", "湿度"],
  ["Gió", "風"],
  ["Lời khuyên sức khỏe", "健康アドバイス"],
  ["Thông báo gần đây", "最近の通知"],
  ["Cập nhật mới", "新しい更新"],
  ["Xem tất cả", "すべて表示"],
  ["Tìm địa điểm", "スポットを探す"],
  ["kết quả", "件の結果"],
  ["Từ khóa", "キーワード"],
  ["Tìm kiếm công viên, gym, khu tập ngoài trời...", "公園、ジム、屋外運動エリアを検索..."],
  ["Bộ lọc", "フィルター"],
  ["Ẩn", "非表示"],
  ["Lọc", "絞り込み"],
  ["Gần đây", "最近"],
  ["Tất cả thời điểm", "すべての期間"],
  ["Đang lọc gần đây", "最近の条件で絞り込み中"],
  ["Hiện tất cả", "すべて表示"],
  ["Kết quả", "結果"],
  ["Địa điểm phù hợp", "該当スポット"],
  ["Hà Nội", "ハノイ"],
  ["Yêu thích", "お気に入り"],
  ["Chi tiết", "詳細"],
  ["Không có địa điểm phù hợp với bộ lọc hiện tại.", "現在のフィルターに一致するスポットはありません。"],
  ["Gợi ý theo AQI", "AQI に基づく提案"],
  ["AQI hiện tại ở mức ", "現在の AQI は "],
  ["Nên ưu tiên công viên nhiều cây xanh hoặc phòng tập kín nếu bạn muốn vận động lâu.", "長く運動したい場合は、木の多い公園か屋内ジムを優先してください。"],
  ["Quay lại", "戻る"],
  ["Lộ trình", "ルート"],
  ["Màn hình chi tiết địa điểm và đánh giá", "スポット詳細とレビュー画面"],
  ["Địa điểm được mô tả theo đúng layout tài liệu: hiển thị điểm an toàn, PM2.5, giới thiệu, và nút xem tất cả bình luận.", "ドキュメントのレイアウトどおりに、セーフティスコア、PM2.5、概要、全コメント表示ボタンを表示します。"],
  ["Trạng thái tốt", "良好な状態"],
  ["Facilities", "設備"],
  ["Nước", "給水"],
  ["bóng râm", "日陰"],
  ["Tiện ích", "設備"],
  ["Giới thiệu ngắn về địa điểm, các điều kiện tập luyện, và lời khuyên theo AQI hiện tại.", "スポットの概要、運動条件、現在の AQI に基づくアドバイスです。"],
  ["Xem tất cả bình luận", "すべてのコメントを表示"],
  ["Trở về", "戻る"],
  ["Mới nhất", "最新"],
  ["Đánh giá cao nhất", "高評価順"],
  ["Tổng quan", "概要"],
  ["Đánh giá từ cộng đồng", "コミュニティのレビュー"],
  ["Hãy đăng nhập để đăng bài đánh giá", "レビューを投稿するにはログインしてください"],
  ["Hãy nhập đánh giá của bạn", "レビューを入力してください"],
  ["Cần đăng nhập để gửi bình luận.", "コメントを送信するにはログインが必要です。"],
  ["Gửi bình luận", "コメントを送信"],
  ["Bản đồ và tìm đường dành cho người dùng đăng nhập", "ログインユーザー向けの地図とルート検索"],
  ["Địa điểm tập luyện", "運動スポット"],
  ["Mở cửa", "営業中"],
  ["Cảnh báo sức khỏe hiện tại dựa trên chỉ số AQI và điều kiện thời tiết.", "現在の健康警告は AQI と天候条件に基づいています。"],
  ["Phản hồi chuyên gia", "専門家の見解"],
  ["Hạn chế vận động cường độ cao", "高強度運動は控えてください"],
  ["Ưu tiên tuyến đường xanh và cân nhắc không gian trong nhà nếu cảm thấy khó chịu.", "グリーンルートを優先し、違和感がある場合は屋内も検討してください。"],
  ["Chi tiết ", "詳細 "],
  ["Hồ sơ và cài đặt", "プロフィールと設定"],
  ["Người dùng", "ユーザー"],
  ["Thành viên SafeMove", "SafeMove メンバー"],
  ["Tình trạng sức khỏe", "健康状態"],
  ["Chưa có dữ liệu tình trạng sức khỏe.", "健康データはまだありません。"],
  ["Thông tin cá nhân", "個人情報"],
  ["Họ và tên", "氏名"],
  ["Số điện thoại", "電話番号"],
  ["Ngưỡng AQI", "AQI しきい値"],
  ["Khi AQI vượt ngưỡng này, ứng dụng sẽ ưu tiên cảnh báo sớm và gợi ý tuyến ít phơi nhiễm hơn.", "このしきい値を超えると、アプリは早めの警告と曝露の少ないルートを優先します。"],
  ["Thông báo", "通知"],
  ["Thông báo đẩy", "プッシュ通知"],
  ["Cập nhật qua email", "メール更新"],
  ["Lưu cài đặt", "設定を保存"],
  ["Đăng xuất", "ログアウト"],
  ["Bảng điều khiển quản trị hệ thống", "システム管理ダッシュボード"],
  ["Quản lý cơ sở", "施設管理"],
  ["Quản lý vi phạm", "違反管理"],
  ["AQI trung bình", "平均 AQI"],
  ["Người dùng hoạt động", "アクティブユーザー"],
  ["Đang chờ xử lý", "処理待ち"],
  ["Cơ sở", "施設"],
  ["Khẩn cấp", "緊急"],
  ["Vi phạm ", "違反 "],
  ["Thống kê nhanh", "クイック統計"],
  ["Avg AQI", "平均 AQI"],
  ["Reports", "レポート"],
  ["Facilities", "施設"],
  ["Trung bình thành phố", "市内平均"],
  ["Cần kiểm duyệt", "審査が必要"],
  ["Đã đăng ký", "登録済み"],
  ["Màn hình quản lý thông tin cơ sở", "施設情報管理画面"],
  ["Thêm cơ sở mới", "新しい施設を追加"],
  ["Màn hình thêm cơ sở mới", "新しい施設追加画面"],
  ["Tên cơ sở", "施設名"],
  ["Địa chỉ", "住所"],
  ["Mô tả", "説明"],
  ["Không gian xanh, có HEPA", "緑のある空間、HEPA あり"],
  ["Lưu", "保存"],
  ["Màn hình quản lý bình luận vi phạm", "違反コメント管理画面"],
  ["Lọc theo địa điểm", "スポットで絞り込む"],
  ["Chưa xử lý", "未処理"],
  ["Đã xóa", "削除済み"],
  ["Xóa", "削除"],
  ["Khôi phục", "復元"],
  ["Màn hình hồ sơ quản trị viên", "管理者プロフィール画面"],
  ["Xác thực", "認証"],
  ["Quản trị viên hệ thống", "システム管理者"],
  ["Đã xác nhận", "確認済み"],
  ["Họ tên", "氏名"],
  ["Số điện thoại", "電話番号"],
  ["Quyền truy cập", "アクセス権限"],
]);

updateFile("FE/src/components/RoutePlannerView.tsx", [
  ["Bạn đang lệch tuyến khoảng ", "ルートから約 "],
  [" Nếu tiếp tục sẽ cập nhật lại.", " このまま進むと再計算します。"],
  ["Đang tải", "読み込み中"],
  ["phút", "分"],
]);
